---
- name: Reset antigen cache
  command: "timeout 10s /bin/zsh -c 'source {{ zsh_config }}; antigen reset'"
  become: yes
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false

# it will fail, but it install all bundles for user
- name: Update antigen bundles
  command: "timeout 30s /bin/zsh -c 'source {{ zsh_config }}; antigen update'"
  become: yes
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false
