- name: Get Ubuntu/Debian users's home path
  shell: "egrep '^.*:.*:[1-9][0-9]{3,4}:.*:.*:.*:.*(bash|zsh)$' /etc/passwd | awk -F: '{print $6}'"
  register: paths
  when: ansible_os_family == 'Debian'
  changed_when: false

- name: Get Ubuntu/Debian users
  shell: "egrep '^.*:.*:[1-9][0-9]{3,4}:.*:.*:.*:.*(bash|zsh)$' /etc/passwd | awk -F: '{print $1}'"
  register: users
  when: ansible_os_family == 'Debian' and paths is defined and paths.stdout != ""
  changed_when: false
- name: Format user list
  set_fact:
    list_users: "{{['root','root'] + users.stdout.splitlines()| list}}"
  when: ansible_os_family == 'Debian' and paths is defined and paths.stdout != ""

- name: Merge the users path and root/skel to list
  set_fact:
    allpaths: "{{ ['/root','/etc/skel'] + paths.stdout.splitlines()| list }}"
  when: zsh_shared and paths is defined and paths.stdout != ""
- name: Use only root/skel for the list (no users found)
  set_fact:
    allpaths: "{{ ['/root','/etc/skel']}}"
  when: paths is defined and paths.stdout == ""

- name: Install .zshrc in {{allpaths | join(',')}}
  become: yes
  copy:
    content: source /usr/share/zsh-config/.zshrc
    dest: "{{item}}/.zshrc"
    owner: "{{list_users[id]| default('root')}}"
    mode: '0644'
  loop: "{{allpaths}}"
  loop_control:
    index_var: id
  when: allpaths is defined